2022-10-01 01:13:53,762 ERROR: Exception on /login [GET] [in /home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/auth/routes.py", line 27, in login
    return render_template('auth/login.html')
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/auth/login.html", line 54, in top-level template code
    <a href="{{ url_for('auht.reset_password_request') }}" class="">Forgot password?</a>
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auht.reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2022-10-01 01:16:02,125 INFO: Myblog startup [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-01 01:16:06,084 ERROR: Exception on /login [GET] [in /home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/auth/routes.py", line 27, in login
    return render_template('auth/login.html')
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/auth/login.html", line 54, in top-level template code
    <a href="{{ url_for('auht.reset_password_request') }}" class="">Forgot password?</a>
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auht.reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2022-10-01 01:20:03,396 INFO: Myblog startup [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-01 01:20:48,407 INFO: Myblog startup [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-01 01:26:07,560 INFO: Myblog startup [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-01 01:26:10,224 ERROR: Exception on /login [GET] [in /home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/auth/routes.py", line 27, in login
    return render_template('auth/login.html')
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/auth/login.html", line 54, in top-level template code
    <a href="{{ url_for('auht.reset_password_request') }}" class="">Forgot password?</a>
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auht.reset_password_request'. Did you mean 'auth.reset_password_request' instead?
2022-10-01 01:30:36,550 INFO: Myblog startup [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-01 01:31:21,282 INFO: Myblog startup [in /home/duonglieumoc/OneDrive/python_program/website/app/__init__.py:75]
2022-10-01 01:31:39,807 ERROR: Exception on /login [GET] [in /home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py:1741]
Traceback (most recent call last):
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/auth/routes.py", line 27, in login
    return render_template('auth/login.html')
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/duonglieumoc/OneDrive/python_program/website/app/templates/auth/login.html", line 54, in top-level template code
    <a href="{{ url_for('auht.reset_password_request') }}" class="">Forgot password?</a>
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2031, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/flask/app.py", line 2020, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/home/duonglieumoc/.local/lib/python3.10/site-packages/werkzeug/routing/map.py", line 917, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'auht.reset_password_request'. Did you mean 'auth.reset_password_request' instead?
